name: Terraform

on:
  workflow_call:


jobs:
  terraform:    
    runs-on: ${{ inputs.runner-label }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_dir }}

    steps:
    # https://github.com/actions/setup-node
    - name: Setup Node
      if: inputs.runner-label != 'ubuntu-linux'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
        
    # - name: Terraform Init
    #   run: terraform init

    - name: Terraform Format
      run: terraform fmt -check        