name: Sonar

on:
  workflow_call:
    inputs: 
      runner-label:
        required: false
        type: string
        default: self-hosted      
    secrets:
      SONAR_TOKEN: 
        required: true
      SONAR_HOST_URL:
        required: true

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ${{ inputs.runner-label }}

    steps:
    # https://github.com/actions/setup-node 
    # This is for self-hosted Runners.
    - name: Setup Node
      if: inputs.runner-label != 'ubuntu-linux'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - uses: actions/checkout@v3
      with:        
        fetch-depth: 0

    - name: SonarQube Scan
      id: scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate check
      id: quality-gates
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}