name: Terraform Docs

on:
  workflow_call:
    inputs:
      runner-label:
        required: false
        type: string
        default: self-hosted

jobs:
  terraform-docs:    
    runs-on: ${{ inputs.runner-label }}
    
    steps:
    # https://github.com/actions/setup-node 
    # This is for self-hosted Runners.
    - name: Setup Node
      if: inputs.runner-label != 'ubuntu-linux'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Docs
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        find-dir: ./
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Commit & Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      if: github.ref == 'refs/head/main' && github.event_name == 'push'
