name: Terraform Build

on:
  workflow_call:
    inputs:
      tf-env:
        required: true
        type: string
      oidc:
        required: true
        type: string
      region: 
        required: false
        type: string
        default: eu-west-1        
      runner-label:
        required: false
        type: string
        default: self-hosted
    secrets:
      GH_TOKEN: 
        required: false
jobs:
  tf-plan:          
    runs-on: ${{ inputs.runner-label }}

    strategy:
      matrix: ${{ fromJSON(inputs.tf-env) }}

    permissions:
      packages: write
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
                
    steps:
    # https://github.com/actions/setup-node 
    # This is for self-hosted Runners.
    - name: Setup Node
      if: inputs.runner-label != 'ubuntu-linux'
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.oidc }}
        aws-region: ${{ inputs.region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      run: |
        git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com
        terraform init
      working-directory: ${{ matrix.envs }} 

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ matrix.envs }}       
